# Simple workflow for deploying static content to GitHub Pages
name: Documentation

on:
  push:
    branches: ["master"]
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # TODO: ubuntu slim enough?
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - run: |
          python -m python -m pip install --upgrade pip
          python -m pip install . --group=docs

      # TODO: This gets included in docs/conf.py

      # - name: Sphinx APIDoc
      #   run: |
      #     sphinx-apidoc --force -o docs/source/ .
      - name: Sphinx build
        run: |
          sphinx-build --builder html docs/source/ docs/build/html

      # # TODO: From here only on master branch

      # - name: Setup Pages
      #   uses: actions/configure-pages@v5
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v4
      #   with:
      #     # Upload entire repository
      #     path: './docs/build/html'
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4
